#!/bin/bash
docker exec -u www-data wordpress bash -c "php wp-cli.phar search-replace 'Linens' 'Постільна білизна' --all-tables"
docker exec -u www-data wordpress bash -c "php wp-cli.phar search-replace 'Toiletries' 'Косметичні засоби' --all-tables"
docker exec -u www-data wordpress bash -c "php wp-cli.phar search-replace 'Breakfast' 'Сніданок' --all-tables"
docker exec -u www-data wordpress bash -c "php wp-cli.phar search-replace 'Swimming Pool' 'Басейн' --all-tables"
docker exec -u www-data wordpress bash -c "php wp-cli.phar search-replace 'Wellness Spa' 'Спа-центр' --all-tables"
docker exec -u www-data wordpress bash -c "php wp-cli.phar search-replace 'Fine Dining' 'Ресторан' --all-tables"
docker exec -u www-data wordpress bash -c "php wp-cli.phar search-replace 'In-house Bar' 'Бар' --all-tables"
docker exec -u www-data wordpress bash -c "php wp-cli.phar search-replace 'Banquet Hall' 'Банкетний зал' --all-tables"
echo "Database translation completed remotely."
